apiVersion: v1
kind: Service
metadata:
  name: marketplace-b2b-back-ci-cd-service
  namespace: marketplace-b2b-back-ci-cd-dev
  labels:
    app: marketplace-b2b-back-ci-cd-service
spec:
  type: ClusterIP
  selector:
    app: marketplace-b2b-back-ci-cd-deployment
  ports:
    - name: http
      port: 8000
      targetPort: 8000
