apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-b2b-back-ci-cd-deployment
  namespace: marketplace-b2b-back-ci-cd
  labels:
    app: marketplace-b2b-back-ci-cd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-b2b-back-ci-cd-deployment
  template:
    metadata:
      labels:
        app: marketplace-b2b-back-ci-cd-deployment
        monitoring: enabled-pod
    spec:
      containers:
        - name: marketplace-b2b-back-ci-cd-dev
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          ports:
            - name: metrics
              containerPort: 8082
      restartPolicy: Always
